steps:
  - name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      [
        "build",
        "--build-arg", "BUILDKIT_INLINE_CACHE=1",
        "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:$SHORT_SHA",
        "-t", "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:buildcache",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:$SHORT_SHA"
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:buildcache"
      ]

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:$SHORT_SHA"

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
