@'
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:$SHORT_SHA"
      - "."

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:$SHORT_SHA"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/abfertigung-repo/abfertigung:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
'@ | Set-Content -Encoding UTF8 cloudbuild.yaml